kind: Pod
apiVersion: v1
metadata:
  name: iiscorebox
spec:
  containers:
    - name: myfrontend
      image: mcr.microsoft.com/windows/servercore/iis:latest
      volumeMounts:
      - mountPath: "e:"
        name: disk-volume1
      - mountPath: "f:"
        name: az-file-vol2
  volumes:
    - name: disk-volume1
      persistentVolumeClaim:
        claimName: azure-managed-disk
    - name: az-file-vol2
      persistentVolumeClaim:
        claimName: azure-files      