apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefilestatic
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: azsharevolume123  # make sure this volumeid is unique in the cluster
    volumeAttributes:
      resourceGroup: aks-volume-demo-rg  # Resource group name for the Azure File share ($rg from the setup script)
      shareName: aks-volume-demo-share   # Share name for the Azure File share ($share_name from the setup script)
    nodeStageSecretRef:
      name: aks-volume-demo-storage-key  # Secret name for the Azure Storage account key ($storage_key from the setup script)
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock