apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: static-disk
provisioner: kubernetes.io/azure-disk
volumeBindingMode: WaitForFirstConsumer # Default is Immediate, recommended is WaitForFirstConsumer
allowVolumeExpansion: true # Allows the user to increase PVC request size later